const presName = ["George Washington", "John Adams", "Thomas Jefferson", "James Madison", "James Monroe", "John Quincy Adams", "Andrew Jackson", "Martin Van Buren", "William Henry Harrison", "John Tyler", "James Polk", "Zachary Taylor", "Millard Fillmore", "Franklin Pierce", "James Buchanan", "Abraham Lincoln", "Andrew Johnson", "Ulysses Grant", "Rutherford Hayes", "James Garfield", "Chester Arthur", "Grover Celveland", "Benjamin Harrison", "William McKinley", "Theordore Roosevelt", "William Taft", "Woodrow Wilson", "Warren Harding", "Calvin Coolidge", "Herbert Hoover", "Franklin Roosevelt", "Harry Truman", "Dwight Eisenhower", "John Kennedy", "Lyndon Johnson", "Richard Nixon", "Gerald Ford", "Jimmy Carter", "Ronald Reagan", "George H. W. Bush", "Bill Clinton", "George W. Bush", "Barrack Obama", "Donald Trump", "Joe Biden"]


presData={
    "George Washington": "He is the only US president to have personally led US soldiers into battle while he was serving as the President of the United States",
    "John Adams": "He created the United States Marine Band in 1798 which is the oldest professional musical association in the US",
    "Thomas Jefferson": "He loved to listen to Mocking Birds sing and he kept them as pets",
    "James Madison": "While studying at Princeton he stayed for an extra year which makes him the very first postgraduate student in the US",
    "James Monro": "Monroe was the US president who purchased Florida from the Spanish for five million",
    "John Quincy Adams": "Every morning he would swim in the Potamac river for exercise",
    "Andrew Jackson": "He is the only president to have personally thwarted an assination attempt on his life",
    "Martin Van Buren": "He was the first US president to have been born in the United States when it was its own country and not a British colony",
    "William Henry Harrison": "He only served as president for one month, after which he died of pneumonia",
    "John Tyler": "He had fifteen children the most of any president",
    "James Polk": "For two days every week James Polk held office hours in which any citizen could visit him",
    "Zachary Taylor": "He was unaware that he was nominated as presential candidate until he recieved a letter telling him so",
    "Millard Fillmore": "He did not have a vice president while he was president",
    "Franklin Pierce": "When he was twelve his father made him walk for miles in a thunderstorm",
    "James Buchanan": "He is the only president who has never been married",
    "Abraham Lincoln": "Was a very accomplished wrestler and only ever lost one out of three hundred matches",
    "Andrew Johnson": "Was the first president to ever be impeached",
    "Ulysses Grant": "He was a gifted writer and his autobiography is considered to be one of the best ever written by a former president",
    "Rutherford Hayes": "He and his wife started the tradition of having Easter Egg rolls on the Whitehouse lawn",
    "James Garfield": "Married one of his students while he was teaching classes at a college",
    "Chester Arthur": "He was a very skilled fisherman",
    "Grover Cleveland": "Is the only US president to have served two non consectutive terms",
    "Benjamin Harrison": "Was afraid to touch lightbulbs out of fear of electrocution",
    "William McKinley": "He was the first president to ever ride in an automobile",
    "Theodore Roosevelt": "He was blinded in one eye while boxing in the Whitehouse",
    "William Taft": "Was the fattest president and once got stuck in the Whitehouse bathtub",
    "Woodrow Wilson": "Was the first president from the South since the Civil War",
    "Warren Harding": "Ordered desegregation of the Whitehouse and the District of Columbia",
    "Calvin Coolidge": "Was known for being a man of very few words",
    "Herbert Hoover": "Was a self made millionaire from discovering valuable metals all over the globe",
    "Franklin Roosevelt": "Was a keen stamp collector",
    "Harry Truman": "He did not find out about the nations atomic program until after FDR died and he was sworn in as president",
    "Dwight Eisenhower": "Despite serving for thirty five years in the army and becoming a general, he never once saw active combat",
    "John Kennedy": "Was the first catholic president",
    "Lyndon Johnson": "His first career was that of a teacher",
    "Richard Nixon": "His middlename was Milhous",
    "Gerald Ford": "He served as president and vice president despite never being elected to office",
    "Jimmy Carter": "He was the first person in his family to graduate highschool",
    "Ronald Reagan": "Jellybeans were his favorite snack",
    "George H. W. Bush": "He was the youngest pilot in the navy while he served",
    "Bill Clinton": "He has won two grammy awards",
    "George W Bush": "He is the only president with an MBA",
    "Barrack Obama": "His first job was at baskin robbins scooping icrecream",
    "Donald Trump": "He is the only president to have been impeached twice",
    "Joe Biden": "He is the oldest president in us history"






}

const presidents = [

    {name: 'George Washington', facts: ['(a)He is the only US president to have personally led US soldiers into battle while he was serving as the President of the United States', '(b)While studying at Princeton he stayed for an extra year which makes him the very first postgraduate student in the US', '(c)He loved to listen to Mocking Birds sing and he kept them as pet', '(d)Was a self made millionaire from discovering valuable metals all over the globe'], answer: 0}, 
    {name: 'John Adams', facts: ['(a)Was known for being a man of very few words', '(b)He created the United States Marine Band in 1798 which is the oldest professional musical association in the US', '(c)Despite serving for thirty five years in the army and becoming a general, he never once saw active combat', '(d)He is the only president to have been impeached twice'], answer: 1},
     {name: 'Thomas Jefferson', facts: ['(a)He is the only president to have personally thwarted an assination attempt on his life', '(b)He was a very skilled fisherman', '(c)He loved to listen to Mocking Birds sing and he kept them as pets', '(d)Is the only US president to have served two non consectutive terms'], answer: 2},
     {name: 'James Madison', facts: ['(a)While studying at Princeton he stayed for an extra year which makes him the very first postgraduate student in the US', '(b)Was a very accomplished wrestler and only ever lost one out of three hundred matches', '(c)He was the youngest pilot in the navy while he served', '(d)He and his wife started the tradition of having Easter Egg rolls on the Whitehouse lawn'], answer: 0},
     {name: 'James Monroe', facts: ['(a)Every morning he would swim in the Potamac river for exercise', '(b)Was the fattest president and once got stuck in the Whitehouse bathtub', '(c)Monroe was the US president who purchased Florida from the Spanish for five million', '(d)He has won two grammy awards'], answer: 2},
     {name: 'John Quincy Adams', facts: ['(a)Every morning he would swim in the Potamac river for exercise', '(b)While studying at Princeton he stayed for an extra year which makes him the very first postgraduate student in the US', '(c)He was a gifted writer and his autobiography is considered to be one of the best ever written by a former president', '(d)He has won two grammy awards'], answer: 0},
     {name: "Andrew Jackson", facts: ['(a)He was the first US president to have been born in the United States when it was its own country and not a British colony', '(b)Was afraid to touch lightbulbs out of fear of electrocution', '(c)His first career was that of a teacher', '(d)He is the only president to have personally thwarted an assination attempt on his life'], answer: 3},
     {name: "Martin Van Buren", facts: ['(a)He is the only president who has never been married', '(b)He was the first US president to have been born in the United States when it was its own country and not a British colony', 'Was a self made millionaire from discovering valuable metals all over the globe', '(d)He was the first person in his family to graduate highschool'], answer: 2},
     {name: "William Henry Harrison", facts: ['(a)He had fifteen children the most of any presiden', '(b)He is the only president who has never been married', '(c)He only served as president for one month, after which he died of pneumonia', '(d)He was a very skilled fisherman'], answer: 2},
     {name: "John Tyler", facts: ['(a)When he was twelve his father made him walk for miles in a thunderstorm', '(b)He served as president and vice president despite never being elected to office', '(c)He was the first president to ever ride in an automobile', '(d)He had fifteen children the most of any president'], answer: 3},
     {name: "James Polk", facts: ['(a)For two days every week he held office hours in which any citizen could visit him', '(b)Was the first catholic president', '(c)Married one of his students while he was teaching classes at a college', '(d)He and his wife started the tradition of having Easter Egg rolls on the Whitehouse lawn'], answer: 0},
     {name: "Zachary Taylor", facts: ['(a)He is the oldest president in us history', '(b)He was unaware that he was nominated as presential candidate until he recieved a letter telling him so', 'He was blinded in one eye while boxing in the Whitehouse', '(d)Was known for being a man of very few words'], answer: 1},
     {name: "Millard Fillmore", facts: ['(a)He did not have a vice president while he was president', '(b)Was a keen stamp collector', '(c)Every morning he would swim in the Potamac river for exercise', '(d)He is the only president to have personally thwarted an assination attempt on his life'], answer: 0},
     {name: "Franklin Pierce", facts: ['(a)He is the only president who has never been married', '(b)He had fifteen children the most of any presiden', '(c)When he was twelve his father made him walk for miles in a thunderstorm', '(d)Was afraid to touch lightbulbs out of fear of electrocution'], answer: 2},
     {name: "James Buchanan", facts: ['(a)Was the fattest president and once got stuck in the Whitehouse bathtub', '(b)Despite serving for thirty five years in the army and becoming a general, he never once saw active combat', '(c)His first career was that of a teacher', '(d)He is the only president who has never been married'], answer: 3},
     {name: "Abraham Lincoln", facts: ['(a)Ordered desegregation of the Whitehouse and the District of Columbia', '(b)Was a very accomplished wrestler and only ever lost one out of three hundred matches', '(c)Was the first catholic president', '(d)He was the first person in his family to graduate highschool'], answer: 1},
     {name: "Andrew Johnson", facts: ['(a)Was the first president to ever be impeached', '(b)When he was twelve his father made him walk for miles in a thunderstorm', '(c)He was a very skilled fisherman', '(d)Was a keen stamp collector'], answer: 0},
     {name: "Ulysses Grant", facts: ['(a)He was a very skilled fisherman', '(b)Is the only US president to have served two non consectutive terms', '(c)He was a gifted writer and his autobiography is considered to be one of the best ever written by a former president', '(d)He is the only president to have been impeached twice'], answer: 2},
     {name: "Rutherford Hayes", facts: ['(a)He was the first president to ever ride in an automobile', '(b)He and his wife started the tradition of having Easter Egg rolls on the Whitehouse lawn', '(c)Was known for being a man of very few words', '(d)He was blinded in one eye while boxing in the Whitehouse'], answer: 1},
     {name: "James Garfield", facts: ['(a)Married one of his students while he was teaching classes at a college', '(b)Was afraid to touch lightbulbs out of fear of electrocution', '(c)Jellybeans were his favorite snack', '(d)Was a very accomplished wrestler and only ever lost one out of three hundred matches'], answer: 0},
     {name: "Chester Arthur", facts: ['(a)Was the first president to ever be impeached', '(b)Despite serving for thirty five years in the army and becoming a general, he never once saw active combat', '(c)Was known for being a man of very few words', '(d)He was a very skilled fisherman'], answer: 3},
     {name: "Grover Cleveland", facts: ['(a)He is the only president who has never been married', '(b)Was the fattest president and once got stuck in the Whitehouse bathtub', '(c)Is the only US president to have served two non consectutive terms', '(d)He was the first president to ever ride in an automobile'], answer: 2},
     {name: "Benjamin Harrison", facts: ['(a)Married one of his students while he was teaching classes at a college', '(b)Was afraid to touch lightbulbs out of fear of electrocution', '(c)His middlename was Milhous', '(d)Was the fattest president and once got stuck in the Whitehouse bathtub'], answer: 1},
     {name: "William McKinley", facts: ['(a)He was the first president to ever ride in an automobile', '(b)Is the only US president to have served two non consectutive terms', '(c)His first job was at baskin robbins scooping icrecream', '(d)Was a very accomplished wrestler and only ever lost one out of three hundred matches'], answer: 0},
     {name: "Theodore Roosevelt", facts: ['(a)Was the first president from the South since the Civil War', '(b)He was blinded in one eye while boxing in the Whitehouse', '(c)Was the first catholic president', '(d)He was the first person in his family to graduate highschool'], answer: 1},
     {name: "William Taft", facts: ['(a)When he was twelve his father made him walk for miles in a thunderstorm', '(b)He was a very skilled fisherman', '(c)Was the fattest president and once got stuck in the Whitehouse bathtub', '(d)He has won two grammy awards'], answer: 2},
     {name: "Woodrow Wilson", facts: ['(a)He served as president and vice president despite never being elected to office', '(b)Was the first president from the South since the Civil War', '(c)His middlename was Milhous', '(d)Was afraid to touch lightbulbs out of fear of electrocution'], answer: 1},
     {name: "Warren Harding", facts: ['(a)Was a keen stamp collector', '(b)Is the only US president to have served two non consectutive terms', '(c)He is the only president with an MBA', '(d)Ordered desegregation of the Whitehouse and the District of Columbia'], answer: 3},
     {name: "Calvin Coolidge", facts: ['(a)He is the only president who has never been married', '(b)His first job was at baskin robbins scooping icrecream', '(c)Was known for being a man of very few words', '(d)When he was twelve his father made him walk for miles in a thunderstorm'], answer: 2},
     {name: "Herbert Hoover", facts: ['(a)Was a self made millionaire from discovering valuable metals all over the globe', '(b)He was a very skilled fisherman', '(c)Married one of his students while he was teaching classes at a college', '(d)Was afraid to touch lightbulbs out of fear of electrocution'], answer: 0},
     {name: "Franklin Roosevelt", facts: ['(a)Was the first catholic president', '(b)Was a keen stamp collector', '(c)He is the only president who has never been married', '(d)He was the youngest pilot in the navy while he served'], answer: 1},
     {name: "Harry Truman", facts: ['(a)He did not find out about the nations atomic program until after FDR died and he was sworn in as president', '(b)He and his wife started the tradition of having Easter Egg rolls on the Whitehouse lawn', '(c)Was known for being a man of very few words', '(d)Was a very accomplished wrestler and only ever lost one out of three hundred matches'], answer: 0},
     {name: "Dwight Eisenhower", facts: ['(a)He is the oldest president in us history', '(b)Is the only US president to have served two non consectutive terms', '(c)Despite serving for thirty five years in the army and becoming a general, he never once saw active combat', '(d)When he was twelve his father made him walk for miles in a thunderstorm'], answer: 2},
     {name: "John Kennedy", facts: ['(a)Ordered desegregation of the Whitehouse and the District of Columbia', '(b)He was a very skilled fisherman', '(c)Jellybeans were his favorite snack', '(d)Was the first catholic president'], answer: 3},
     {name: "Lyndon Johnson", facts: ['(a)He is the only president with an MBA', '(b)His first career was that of a teacher', '(c)Was afraid to touch lightbulbs out of fear of electrocution', '(d)His first job was at baskin robbins scooping icrecream'], answer: 1},
     {name: "Richard Nixon", facts: ['(a)His middlename was Milhous', '(b)He is the only president who has never been married', '(c)He has won two grammy awards', '(d)Was the fattest president and once got stuck in the Whitehouse bathtub'], answer: 0},
     {name: "Gerald Ford", facts: ['(a)When he was twelve his father made him walk for miles in a thunderstorm', '(b)He was a very skilled fisherman', '(c)He served as president and vice president despite never being elected to office', '(d)Was a keen stamp collector'], answer: 2},
     {name: "Jimmy Carter", facts: ['(a)He is the only president with an MBA', '(b)He was the first person in his family to graduate highschool', '(c)Is the only US president to have served two non consectutive terms', '(d)He was blinded in one eye while boxing in the Whitehouse'], answer: 1},
     {name: "Ronald Reagan", facts: ['(a)Married one of his students while he was teaching classes at a college', '(b)His first job was at baskin robbins scooping icrecream', '(c)He loved to listen to Mocking Birds sing and he kept them as pets\n (d)Jellybeans were his favorite snack'], answer: 3},
     {name: "George H. W. Bush", facts: ['(a)He was the youngest pilot in the navy while he served', '(b)Was the first president from the South since the Civil War', '(c)He had fifteen children the most of any presiden', '(d)He has won two grammy awards'], answer: 0},
     {name: "Bill Clinton", facts: ['(a)He was unaware that he was nominated as presential candidate until he recieved a letter telling him so', '(b)He has won two grammy awards', '(c)He is the only president to have been impeached twice', '(d)He is the only president with an MBA'], answer: 1},
     {name: "George W Bush", facts: ['(a)Married one of his students while he was teaching classes at a college',  '(b)Was a keen stamp collector', '(c)He is the only president with an MBA', '(d)He was a very skilled fisherman'], answer: 2},
     {name: "Barrack Obama", facts: ['(a)While studying at Princeton he stayed for an extra year which makes him the very first postgraduate student in the US', '(b)His first job was at baskin robbins scooping icrecream', '(c)Jellybeans were his favorite snack', '(d)Was the first catholic president'], answer: 1},
     {name: "Donald Trump", facts: ['(a)He is the only president to have been impeached twice', '(b)He is the oldest president in us history', '(c)Was afraid to touch lightbulbs out of fear of electrocution', '(d)Was the fattest president and once got stuck in the Whitehouse bathtub'], answer: 1},
     {name: "Joe Biden", facts: ['(a)His first career was that of a teacher', '(b)His first job was at baskin robbins scooping icrecream', '(c)He is the oldest president in us history', '(d)Was a keen stamp collector'], answer: 2}
    ]